---
- hosts: localhost
  vars_files:
    - vars.yml

  tasks:

# cat jwt_dev.key | ansible-vault encrypt_string --vault-id @prompt --stdin-name 'private_key'
# ansible-playbook vault-secrets.yml --vault-id @prompt --extra-vars "env=dev"